run:
  timeout: 10m
  go: "1.24.2"
  issues:
    exclude-dirs:
      - vendor
      - node_modules
  fast: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gocyclo
    - revive
    - gofmt
    - goimports

linters-settings:
  exhaustruct:
    exclude:
      - ".*_test\\.go"
  errcheck:
    check-type-assertions: true
    check-blank: true
  staticcheck:
    checks: ["all", "-SA1019"]
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: var-naming
        severity: warning
      - name: empty-block
        severity: error

issues:
  exclude-patterns:
    - ".*_generated\\.go"
    - ".*_test\\.go"
  exclude-rules:
    - path: "vendor/.*"
      linters:
        - all

output:
  formats: colored-line-number
  sort-results: true
