// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aaravmahajanofficial/scalable-ecommerce-platform/internal/models"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// CreateOrder provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) CreateOrder(ctx context.Context, order *models.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderRepository_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx
//   - order
func (_e *MockOrderRepository_Expecter) CreateOrder(ctx interface{}, order interface{}) *MockOrderRepository_CreateOrder_Call {
	return &MockOrderRepository_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, order)}
}

func (_c *MockOrderRepository_CreateOrder_Call) Run(run func(ctx context.Context, order *models.Order)) *MockOrderRepository_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Order))
	})
	return _c
}

func (_c *MockOrderRepository_CreateOrder_Call) Return(err error) *MockOrderRepository_CreateOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_CreateOrder_Call) RunAndReturn(run func(ctx context.Context, order *models.Order) error) *MockOrderRepository_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) GetOrderByID(ctx context.Context, id uuid.UUID) (*models.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_GetOrderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByID'
type MockOrderRepository_GetOrderByID_Call struct {
	*mock.Call
}

// GetOrderByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockOrderRepository_Expecter) GetOrderByID(ctx interface{}, id interface{}) *MockOrderRepository_GetOrderByID_Call {
	return &MockOrderRepository_GetOrderByID_Call{Call: _e.mock.On("GetOrderByID", ctx, id)}
}

func (_c *MockOrderRepository_GetOrderByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrderRepository_GetOrderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrderRepository_GetOrderByID_Call) Return(order *models.Order, err error) *MockOrderRepository_GetOrderByID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_GetOrderByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*models.Order, error)) *MockOrderRepository_GetOrderByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrdersByCustomer provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) ListOrdersByCustomer(ctx context.Context, customerID uuid.UUID, page int, size int) ([]models.Order, int, error) {
	ret := _mock.Called(ctx, customerID, page, size)

	if len(ret) == 0 {
		panic("no return value specified for ListOrdersByCustomer")
	}

	var r0 []models.Order
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]models.Order, int, error)); ok {
		return returnFunc(ctx, customerID, page, size)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []models.Order); ok {
		r0 = returnFunc(ctx, customerID, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int); ok {
		r1 = returnFunc(ctx, customerID, page, size)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = returnFunc(ctx, customerID, page, size)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockOrderRepository_ListOrdersByCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrdersByCustomer'
type MockOrderRepository_ListOrdersByCustomer_Call struct {
	*mock.Call
}

// ListOrdersByCustomer is a helper method to define mock.On call
//   - ctx
//   - customerID
//   - page
//   - size
func (_e *MockOrderRepository_Expecter) ListOrdersByCustomer(ctx interface{}, customerID interface{}, page interface{}, size interface{}) *MockOrderRepository_ListOrdersByCustomer_Call {
	return &MockOrderRepository_ListOrdersByCustomer_Call{Call: _e.mock.On("ListOrdersByCustomer", ctx, customerID, page, size)}
}

func (_c *MockOrderRepository_ListOrdersByCustomer_Call) Run(run func(ctx context.Context, customerID uuid.UUID, page int, size int)) *MockOrderRepository_ListOrdersByCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockOrderRepository_ListOrdersByCustomer_Call) Return(orders []models.Order, n int, err error) *MockOrderRepository_ListOrdersByCustomer_Call {
	_c.Call.Return(orders, n, err)
	return _c
}

func (_c *MockOrderRepository_ListOrdersByCustomer_Call) RunAndReturn(run func(ctx context.Context, customerID uuid.UUID, page int, size int) ([]models.Order, int, error)) *MockOrderRepository_ListOrdersByCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderStatus provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) UpdateOrderStatus(ctx context.Context, id uuid.UUID, status models.OrderStatus) (*models.Order, error) {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderStatus")
	}

	var r0 *models.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.OrderStatus) (*models.Order, error)); ok {
		return returnFunc(ctx, id, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.OrderStatus) *models.Order); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, models.OrderStatus) error); ok {
		r1 = returnFunc(ctx, id, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_UpdateOrderStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderStatus'
type MockOrderRepository_UpdateOrderStatus_Call struct {
	*mock.Call
}

// UpdateOrderStatus is a helper method to define mock.On call
//   - ctx
//   - id
//   - status
func (_e *MockOrderRepository_Expecter) UpdateOrderStatus(ctx interface{}, id interface{}, status interface{}) *MockOrderRepository_UpdateOrderStatus_Call {
	return &MockOrderRepository_UpdateOrderStatus_Call{Call: _e.mock.On("UpdateOrderStatus", ctx, id, status)}
}

func (_c *MockOrderRepository_UpdateOrderStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status models.OrderStatus)) *MockOrderRepository_UpdateOrderStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.OrderStatus))
	})
	return _c
}

func (_c *MockOrderRepository_UpdateOrderStatus_Call) Return(order *models.Order, err error) *MockOrderRepository_UpdateOrderStatus_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_UpdateOrderStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status models.OrderStatus) (*models.Order, error)) *MockOrderRepository_UpdateOrderStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePaymentStatus provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) UpdatePaymentStatus(ctx context.Context, id uuid.UUID, status models.PaymentStatus, paymentIntentID string) error {
	ret := _mock.Called(ctx, id, status, paymentIntentID)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.PaymentStatus, string) error); ok {
		r0 = returnFunc(ctx, id, status, paymentIntentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_UpdatePaymentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePaymentStatus'
type MockOrderRepository_UpdatePaymentStatus_Call struct {
	*mock.Call
}

// UpdatePaymentStatus is a helper method to define mock.On call
//   - ctx
//   - id
//   - status
//   - paymentIntentID
func (_e *MockOrderRepository_Expecter) UpdatePaymentStatus(ctx interface{}, id interface{}, status interface{}, paymentIntentID interface{}) *MockOrderRepository_UpdatePaymentStatus_Call {
	return &MockOrderRepository_UpdatePaymentStatus_Call{Call: _e.mock.On("UpdatePaymentStatus", ctx, id, status, paymentIntentID)}
}

func (_c *MockOrderRepository_UpdatePaymentStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status models.PaymentStatus, paymentIntentID string)) *MockOrderRepository_UpdatePaymentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.PaymentStatus), args[3].(string))
	})
	return _c
}

func (_c *MockOrderRepository_UpdatePaymentStatus_Call) Return(err error) *MockOrderRepository_UpdatePaymentStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_UpdatePaymentStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status models.PaymentStatus, paymentIntentID string) error) *MockOrderRepository_UpdatePaymentStatus_Call {
	_c.Call.Return(run)
	return _c
}
