// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// RateLimitRepository is an autogenerated mock type for the RateLimitRepository type
type RateLimitRepository struct {
	mock.Mock
}

// CheckLoginRateLimit provides a mock function with given fields: ctx, username
func (_m *RateLimitRepository) CheckLoginRateLimit(ctx context.Context, username string) (bool, int, int, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for CheckLoginRateLimit")
	}

	var r0 bool
	var r1 int
	var r2 int
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, int, int, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) int); ok {
		r2 = rf(ctx, username)
	} else {
		r2 = ret.Get(2).(int)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string) error); ok {
		r3 = rf(ctx, username)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// NewRateLimitRepository creates a new instance of RateLimitRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRateLimitRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RateLimitRepository {
	mock := &RateLimitRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
