// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/aaravmahajanofficial/scalable-ecommerce-platform/internal/models"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CartService is an autogenerated mock type for the CartService type
type CartService struct {
	mock.Mock
}

// AddItem provides a mock function with given fields: ctx, customerID, req
func (_m *CartService) AddItem(ctx context.Context, customerID uuid.UUID, req *models.AddItemRequest) (*models.Cart, error) {
	ret := _m.Called(ctx, customerID, req)

	if len(ret) == 0 {
		panic("no return value specified for AddItem")
	}

	var r0 *models.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *models.AddItemRequest) (*models.Cart, error)); ok {
		return rf(ctx, customerID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *models.AddItemRequest) *models.Cart); ok {
		r0 = rf(ctx, customerID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *models.AddItemRequest) error); ok {
		r1 = rf(ctx, customerID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCart provides a mock function with given fields: ctx, userId
func (_m *CartService) CreateCart(ctx context.Context, userId uuid.UUID) (*models.Cart, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for CreateCart")
	}

	var r0 *models.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Cart, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Cart); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCart provides a mock function with given fields: ctx, customerID
func (_m *CartService) GetCart(ctx context.Context, customerID uuid.UUID) (*models.Cart, error) {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 *models.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Cart, error)); ok {
		return rf(ctx, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Cart); ok {
		r0 = rf(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateQuantity provides a mock function with given fields: ctx, customerID, req
func (_m *CartService) UpdateQuantity(ctx context.Context, customerID uuid.UUID, req *models.UpdateQuantityRequest) (*models.Cart, error) {
	ret := _m.Called(ctx, customerID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQuantity")
	}

	var r0 *models.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *models.UpdateQuantityRequest) (*models.Cart, error)); ok {
		return rf(ctx, customerID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *models.UpdateQuantityRequest) *models.Cart); ok {
		r0 = rf(ctx, customerID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *models.UpdateQuantityRequest) error); ok {
		r1 = rf(ctx, customerID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCartService creates a new instance of CartService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartService {
	mock := &CartService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
